version: '3'
services:
  backend-app:
    build: ./backend-app
    container_name: backend_app
    ports:
      - "8081:8081"
    volumes:
      - ./backend-app/uploads:/app/uploads
      - ./backend-app/samples:/app/samples
      - ./backend-app/plugins:/app/plugins
    restart: always

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice_server
    ports:
      - "8082:80"
    environment:
      # Tắt JWT đi để anh dễ test trên Localhost không bị lỗi chặn Token
      - JWT_ENABLED=false
      # Cho phép truy cập IP nội bộ (Sửa lỗi SSRF chặn IP Private 192.168.x.x)
      - ALLOW_PRIVATE_IP_ADDRESS=true
    restart: always
