version: '3'
services:
  backend-app:
    build: ./backend-app
    container_name: backend_app
    expose:
      - "8081"
    volumes:
      - ./backend-app/uploads:/app/uploads
      - ./backend-app/samples:/app/samples
      - ./env.js:/app/env.js
    restart: always

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice_server
    expose:
      - "80"
    environment:
      - JWT_ENABLED=false
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8070:80"
    volumes:
      # Config nginx
      - ./backend-app/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend-app
      - onlyoffice
    restart: always
