USE [QLTiec]
GO

/*
  Bổ sung caption tiếng Việt cho từ điển field dùng chung.
  Chỉ cập nhật field chưa được đặt caption; không ghi đè caption nghiệp vụ đã có.
*/
SET XACT_ABORT ON
GO

BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @Captions TABLE (
        FieldName SYSNAME NOT NULL PRIMARY KEY,
        CaptionVN NVARCHAR(255) NOT NULL
    );

    INSERT INTO @Captions (FieldName, CaptionVN)
    VALUES
        ('BanTang', N'Số bàn tặng'),
        ('BanTang_Cu', N'Số bàn tặng cũ'),
        ('AutoID', N'Mã tự động'),
        ('BenAChucVu', N'Chức vụ bên A'),
        ('BenAChucVuDaiDien', N'Chức vụ đại diện bên A'),
        ('BenADaiDien', N'Đại diện bên A'),
        ('BenAEmail', N'Email bên A'),
        ('BenAMST', N'Mã số thuế bên A'),
        ('BenANguoiDaiDien', N'Người đại diện bên A'),
        ('BenANhanVienPhuTrach', N'Nhân viên phụ trách bên A'),
        ('BenASDT', N'Số điện thoại bên A'),
        ('BenASDTNhanVien', N'Số điện thoại nhân viên bên A'),
        ('BenATenCongTy', N'Tên công ty bên A'),
        ('BenBCCCD', N'CCCD bên B'),
        ('BenBChucVu', N'Chức vụ bên B'),
        ('BenBDaiDien', N'Đại diện bên B'),
        ('BenBDiaChi', N'Địa chỉ bên B'),
        ('BenBDienThoai', N'Điện thoại bên B'),
        ('BenBEmail', N'Email bên B'),
        ('BenBTenChuTiec', N'Tên chủ tiệc bên B'),
        ('BenBTenDaiDien', N'Tên đại diện bên B'),
        ('BuoiTiec', N'Buổi tiệc'),
        ('CocLan1BangChu', N'Tiền cọc lần 1 bằng chữ'),
        ('CocLan1SoTien', N'Số tiền cọc lần 1'),
        ('CocLan2BangChu', N'Tiền cọc lần 2 bằng chữ'),
        ('CocLan2SoTien', N'Số tiền cọc lần 2'),
        ('CocNam', N'Năm đặt cọc'),
        ('CocNgay', N'Ngày đặt cọc'),
        ('CocThang', N'Tháng đặt cọc'),
        ('DanhSachChiPhi', N'Danh sách chi phí'),
        ('DanhSachDichVu', N'Danh sách dịch vụ'),
        ('DanhSachMenu', N'Danh sách thực đơn'),
        ('DanhSachNgay', N'Danh sách ngày'),
        ('DanhSachSanh', N'Danh sách sảnh'),
        ('DanhSachThucUong', N'Danh sách thức uống'),
        ('DiaDiemTiec', N'Địa điểm tiệc'),
        ('DiaDiemTrienLam', N'Địa điểm triển lãm'),
        ('DichVuTinhPhi', N'Dịch vụ tính phí'),
        ('DichVuTinhPhiPhuLuc', N'Dịch vụ tính phí phụ lục'),
        ('DieuKhoanBoSung', N'Điều khoản bổ sung'),
        ('DonGiaBanTiec', N'Đơn giá bàn tiệc'),
        ('DonGiaBanTiec_Cu', N'Đơn giá bàn tiệc cũ'),
        ('Dot1BangChu', N'Thanh toán đợt 1 bằng chữ'),
        ('Dot1HinhThuc', N'Hình thức thanh toán đợt 1'),
        ('Dot1Ngay', N'Ngày thanh toán đợt 1'),
        ('Dot1SoTien', N'Số tiền thanh toán đợt 1'),
        ('Dot2HinhThuc', N'Hình thức thanh toán đợt 2'),
        ('Dot2SoTien', N'Số tiền thanh toán đợt 2'),
        ('DotCuoiGhiChu', N'Ghi chú đợt cuối'),
        ('DSKhuyenMai', N'Danh sách khuyến mãi'),
        ('DVTlon', N'Đơn vị tính lớn'),
        ('DVTnho', N'Đơn vị tính nhỏ'),
        ('FieldName', N'Tên trường'),
        ('FormatID', N'Mã định dạng'),
        ('HanThanhToanDot2', N'Hạn thanh toán đợt 2'),
        ('HDDiaChi', N'Địa chỉ hóa đơn'),
        ('HDEmail', N'Email hóa đơn'),
        ('HDMaSoThue', N'Mã số thuế hóa đơn'),
        ('HDTenCty', N'Tên công ty hóa đơn'),
        ('HinhThuc', N'Hình thức'),
        ('HinhThucThanhToanDot2', N'Hình thức thanh toán đợt 2'),
        ('Id', N'Mã'),
        ('IsBold', N'In đậm'),
        ('IsLoaixuat', N'Là loại xuất'),
        ('IsSuagia', N'Cho phép sửa giá'),
        ('JsonBanTiec', N'Dữ liệu bàn tiệc'),
        ('JsonDichVu', N'Dữ liệu dịch vụ'),
        ('JsonLichTrinh', N'Dữ liệu lịch trình'),
        ('JsonPhatSinh', N'Dữ liệu phát sinh'),
        ('JsonSanhTiec', N'Dữ liệu sảnh tiệc'),
        ('JsonThucUong', N'Dữ liệu thức uống'),
        ('KhachToiThieu', N'Số khách tối thiểu'),
        ('Kemtheo', N'Kèm theo'),
        ('KichThuocSanh', N'Kích thước sảnh'),
        ('KichThuocSanhPhu', N'Kích thước sảnh phụ'),
        ('KichThuocSanKhau', N'Kích thước sân khấu'),
        ('KichThuocSanKhauPhu', N'Kích thước sân khấu phụ'),
        ('LichTrinh', N'Lịch trình'),
        ('LichTrinhThanhToan', N'Lịch trình thanh toán'),
        ('LoaiHinhSuKien', N'Loại hình sự kiện'),
        ('LoaiDiaDiem', N'Loại địa điểm'),
        ('MaChungTu', N'Mã chứng từ'),
        ('MaxLength', N'Độ dài tối đa'),
        ('MaxValue', N'Giá trị tối đa'),
        ('Mayin', N'Máy in'),
        ('MenuTiec', N'Thực đơn tiệc'),
        ('MenuTongCong', N'Tổng cộng thực đơn'),
        ('MinValue', N'Giá trị tối thiểu'),
        ('MucPhiPhucVu', N'Mức phí phục vụ'),
        ('NamLapHD', N'Năm lập hợp đồng'),
        ('NamLapPL', N'Năm lập phụ lục'),
        ('NamToChuc', N'Năm tổ chức'),
        ('NamToChucAmLich', N'Năm tổ chức âm lịch'),
        ('NgayLapHD', N'Ngày lập hợp đồng'),
        ('NgayLapPL', N'Ngày lập phụ lục'),
        ('NgayThanhToanDatCoc', N'Ngày thanh toán đặt cọc'),
        ('NgayToChuc_Cu', N'Ngày tổ chức cũ'),
        ('NgayToChucAmLich', N'Ngày tổ chức âm lịch'),
        ('NVLap', N'Nhân viên lập'),
        ('OutNoiDung', N'Nội dung xuất'),
        ('PhiBuNTL', N'Phí bù NTL'),
        ('PhiBuTTS', N'Phí bù TTS'),
        ('PhiThueSanhNgoaiGio', N'Phí thuê sảnh ngoài giờ'),
        ('QuyMoBanDen', N'Quy mô bàn đến'),
        ('QuyMoBanDen_Cu', N'Quy mô bàn đến cũ'),
        ('QuyMoBanTu', N'Quy mô bàn từ'),
        ('QuyMoBanTu_Cu', N'Quy mô bàn từ cũ'),
        ('Sanh', N'Sảnh'),
        ('SanhDat2', N'Sảnh đặt thứ hai'),
        ('SanhQuyMoMax', N'Quy mô sảnh tối đa'),
        ('SanhQuyMoMin', N'Quy mô sảnh tối thiểu'),
        ('SetupBatDau', N'Bắt đầu thiết lập'),
        ('SetupKetThuc', N'Kết thúc thiết lập'),
        ('SetupNoiDung1', N'Nội dung thiết lập 1'),
        ('SetupNoiDung2', N'Nội dung thiết lập 2'),
        ('SoBanChinhThuc', N'Số bàn chính thức'),
        ('SoBanChinhThuc_Cu', N'Số bàn chính thức cũ'),
        ('SoBanDuPhong', N'Số bàn dự phòng'),
        ('SoBanDuPhong_Cu', N'Số bàn dự phòng cũ'),
        ('SoKhachDiemDanh', N'Số khách điểm danh'),
        ('SoKhachTrenBan', N'Số khách trên bàn'),
        ('SoKhachTrenBan_Cu', N'Số khách trên bàn cũ'),
        ('SoTienConLai', N'Số tiền còn lại'),
        ('SoTienConLaiBangChu', N'Số tiền còn lại bằng chữ'),
        ('SoTienDaDatCoc', N'Số tiền đã đặt cọc'),
        ('Status', N'Trạng thái'),
        ('STT', N'Số thứ tự'),
        ('SucChuaToiDa', N'Sức chứa tối đa'),
        ('SucChuaToiDaPhu', N'Sức chứa tối đa sảnh phụ'),
        ('SucChuaToiThieuPhu', N'Sức chứa tối thiểu sảnh phụ'),
        ('TaiKhoanCo', N'Tài khoản có'),
        ('TaiKhoanNo', N'Tài khoản nợ'),
        ('TemplateFile', N'Tệp mẫu'),
        ('TenSanhTiecPhu', N'Tên sảnh tiệc phụ'),
        ('Tenhangkhongdau', N'Tên hàng không dấu'),
        ('TenSanKhau', N'Tên sân khấu'),
        ('TenSanKhauPhu', N'Tên sân khấu phụ'),
        ('Tentiec', N'Tên tiệc'),
        ('TheVIP', N'Thẻ VIP'),
        ('ThangLapHD', N'Tháng lập hợp đồng'),
        ('ThangLapPL', N'Tháng lập phụ lục'),
        ('ThangToChuc', N'Tháng tổ chức'),
        ('ThangToChucAmLich', N'Tháng tổ chức âm lịch'),
        ('ThanhToanDot2SoTien', N'Số tiền thanh toán đợt 2'),
        ('ThoaThuanPhuLucKhac', N'Thỏa thuận phụ lục khác'),
        ('TiecGioBatDau', N'Giờ bắt đầu tiệc'),
        ('TiecGioKetThuc', N'Giờ kết thúc tiệc'),
        ('TiecLoaiTiec', N'Loại tiệc'),
        ('TiecNamAL', N'Năm tổ chức âm lịch'),
        ('TiecNamDL', N'Năm tổ chức dương lịch'),
        ('TiecNgayAL', N'Ngày tổ chức âm lịch'),
        ('TiecNgayDL', N'Ngày tổ chức dương lịch'),
        ('TiecSanhTiec', N'Sảnh tiệc'),
        ('TiecSoBanChinhThuc', N'Số bàn chính thức'),
        ('TiecSoBanDuPhong', N'Số bàn dự phòng'),
        ('TiecSoBanTang', N'Số bàn tặng'),
        ('TiecSoKhach1Ban', N'Số khách một bàn'),
        ('TiecThangAL', N'Tháng tổ chức âm lịch'),
        ('TiecThangDL', N'Tháng tổ chức dương lịch'),
        ('TieuDePhieu', N'Tiêu đề phiếu'),
        ('TKCo', N'Tài khoản có'),
        ('TKNo', N'Tài khoản nợ'),
        ('ToChucNoiDung', N'Nội dung tổ chức'),
        ('TongCongChuaVAT', N'Tổng cộng chưa VAT'),
        ('TongGiaTriQuyetToan', N'Tổng giá trị quyết toán'),
        ('TongGiaTriQuyetToanBangChu', N'Tổng giá trị quyết toán bằng chữ'),
        ('TongGiaTriTamTinh', N'Tổng giá trị tạm tính'),
        ('TongGiaTriTamTinh_Cu', N'Tổng giá trị tạm tính cũ'),
        ('TongGiaTriTamTinhBangChu', N'Tổng giá trị tạm tính bằng chữ'),
        ('TongThanhTien', N'Tổng thành tiền'),
        ('TongTienFormat', N'Tổng tiền hiển thị'),
        ('UserAutoID', N'Mã tự động'),
        ('VAT10', N'Thuế VAT 10%'),
        ('VAT8', N'Thuế VAT 8%'),
        ('Xuatxuid', N'Mã xuất xứ');

    UPDATE fieldDictionary
    SET fieldDictionary.CaptionVN = caption.CaptionVN
    FROM dbo.SY_FmtFldTbl fieldDictionary
    INNER JOIN @Captions caption ON caption.FieldName = fieldDictionary.FieldName
    WHERE NULLIF(LTRIM(RTRIM(fieldDictionary.CaptionVN)), '') IS NULL
       OR LOWER(fieldDictionary.CaptionVN) = LOWER(fieldDictionary.FieldName);

    DECLARE @UpdatedRows INT = @@ROWCOUNT;

    COMMIT TRANSACTION;

    SELECT @UpdatedRows AS UpdatedRows;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
