/**
 * Màn hình Phân quyền Cán bộ
 */
var PermissionsPage = (function () {
  var $container;

  var groups = window.MockData ? window.MockData.groups : [];
  var modules = window.MockData ? window.MockData.permissionModules : [];

  function render(containerElement) {
    $container = containerElement;

    var html = `
      <div class="page-title-bar">
        <span>Phân quyền Nhóm Người dùng</span>
      </div>

      <div class="row" style="animation: slideUp 0.3s ease forwards; display: flex; gap: 20px; flex-wrap: wrap;">
        
        <!-- CỘT TRÁI: DANH SÁCH NHÓM -->
        <div style="flex: 1 1 250px; max-width: 100%;">
          <div class="card" style="height: 100%;">
            <div class="card-header" style="background:#f8fafc;">
              <h3 style="font-size: var(--font-size-md); margin:0; display:flex; align-items:center; gap:6px;">
                <span class="material-symbols-outlined" style="font-size:var(--font-size-lg);">group</span> Các Nhóm Quyền
              </h3>
            </div>
            <div class="card-body" style="padding: 0;">
              <ul class="group-list" id="group-list" style="list-style: none; margin: 0; padding: 0;">
              </ul>
            </div>
          </div>
        </div>

        <!-- CỘT PHẢI: MA TRẬN QUYỀN -->
        <div style="flex: 999 1 400px; max-width: 100%;">
          <div class="card" style="height: 100%; overflow: hidden; display: flex; flex-direction: column;">
            <div class="card-header" style="display:flex; justify-content:space-between; align-items:center; background:#f8fafc;">
              <h3 style="font-size: var(--font-size-md); margin:0;" id="matrix-title">Quyền hạn của: Admin</h3>
              <button class="btn btn-primary" id="btn-save-permission" style="padding: 4px 12px; font-size:var(--font-size-sm);">Lưu Thay Đổi</button>
            </div>
            <div class="card-body table-wrapper" style="padding:0; border-radius:0 0 8px 8px; width: 100%; max-width: 100%; overflow-x: auto;">
              <table class="data-table" id="permission-table" style="margin:0; min-width: 500px;">
                <thead>
                  <tr>
                    <th style="width: 40px; text-align: center;">STT</th>
                    <th>Tên Chức Năng (Form)</th>
                    <th style="width: 80px; text-align: center;" title="Quyền Xem">Xem</th>
                    <th style="width: 80px; text-align: center;" title="Quyền Thêm">Thêm</th>
                    <th style="width: 80px; text-align: center;" title="Quyền Sửa">Sửa</th>
                    <th style="width: 80px; text-align: center;" title="Quyền Xóa">Xóa</th>
                  </tr>
                </thead>
                <tbody>
                  <!-- GENERATED BY JS -->
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
    `;

    $container.innerHTML = html;
    
    // Tiêm style nhỏ cho group-list
    var style = document.createElement('style');
    style.innerHTML = `
      .group-list li {
        padding: 12px 16px;
        border-bottom: 1px solid var(--color-border);
        cursor: pointer;
        display: flex;
        align-items: center;
        gap: 10px;
        transition: all 0.2s;
        font-weight: 500;
        color: var(--color-text-secondary);
      }
      .group-list li:hover { background: #f1f5f9; color: var(--color-primary); }
      .group-list li.active {
        background: #e0e7ff;
        color: var(--color-primary-dark);
        border-left: 4px solid var(--color-primary);
      }
    `;
    $container.appendChild(style);

    _renderGroups();
    
    $container.querySelector('#btn-save-permission').addEventListener('click', function() {
       alert("Đã lưu phân quyền thành công! (Dữ liệu giả demo)");
    });
  }

  function _renderGroups() {
    var ul = $container.querySelector('#group-list');
    ul.innerHTML = '';
    groups.forEach(function(g, idx) {
      var li = document.createElement('li');
      if(g.selected) li.classList.add('active');
      li.innerHTML = '<span class="material-symbols-outlined" style="font-size:20px;">' + g.icon + '</span>' + g.name;
      
      li.addEventListener('click', function() {
        groups.forEach(gx => gx.selected = false);
        g.selected = true;
        $container.querySelector('#matrix-title').innerText = 'Quyền hạn của: ' + g.name;
        _renderGroups(); // re-render để active state
      });
      ul.appendChild(li);

      // Nếu đang active thì render ma trận tương ứng
      if(g.selected) {
         _renderMatrix(g);
      }
    });
  }

  function _renderMatrix(group) {
    var tbody = $container.querySelector('#permission-table tbody');
    tbody.innerHTML = '';

    // Randomize some fake data based on group for demo
    var isAdmin = group.name === 'Admin';
    var isSales = group.name.includes('lễ tân') || group.name === 'Quản lý';

    modules.forEach(function(modName, idx) {
      var tr = document.createElement('tr');
      tr.innerHTML = `
        <td style="text-align: center;">${idx + 1}</td>
        <td style="font-weight: 500;">${modName}</td>
        <td style="text-align: center;" class="cell-xem"></td>
        <td style="text-align: center;" class="cell-them"></td>
        <td style="text-align: center;" class="cell-sua"></td>
        <td style="text-align: center;" class="cell-xoa"></td>
      `;

      // Tạo Checkbox xịn
      var canXem = isAdmin || isSales;
      var canThem = isAdmin || (isSales && !modName.includes('Hệ thống') && !modName.includes('Báo cáo'));
      var canSua = canThem;
      var canXoa = isAdmin; // Chỉ admin xóa

      function mountCb(cellClass, defaultVal) {
        var wrap = UIControls.createCheckbox({ label: '', checked: defaultVal });
        // Canh giữa checkbox (vì label rỗng)
        wrap.style.justifyContent = 'center';
        tr.querySelector(cellClass).appendChild(wrap);
      }

      mountCb('.cell-xem', canXem);
      mountCb('.cell-them', canThem);
      mountCb('.cell-sua', canSua);
      mountCb('.cell-xoa', canXoa);

      tbody.appendChild(tr);
    });
  }

  return { render: render };
})();
